### ISSUE TITLE
cross lingual experiment baseline features

### ISSUE THREAD

**Issue by ccclyu** [chywang/www19#1]
Hi Chengyu,

Thanks for your nice work!  I have one question about the feature vectors of baseline methods in cross lingual experiments, i.e.  Santus[31], Weeds[49]. In their original papers, they used DSM space co-occurrence vectors. Do you directly use pre-trained fastText word embedding of each term as features?  Would appreciate your reply!

**Comment by chywang** [comment]
Yes. Thank you for your interest.
